### ISSUE TITLE
pass by reference in rb.initRBSensor 

### ISSUE THREAD

**Issue by teeheee** [Robotics-Competence-Center-Illertal-e-V/RocciBoard-Library#1]
In C++ gibt es auch die Möglichkeit ein pass by reference ohne pointer Arithmetik (& vor dem Objekt) auszuführen. Die Kursteilnehmer könnten dann "rb.initRBSensor(compass)" anstatt "rb.initRBSensor(&compass)"  schreiben. Das erspart das Erklären der komplexen Pointer Arithmetik im ersten Kursjahr.

Hier eine detailierte Erklärung:
[https://www.ibm.com/docs/en/zos/2.4.0?topic=calls-pass-by-reference-c-only](https://www.ibm.com/docs/en/zos/2.4.0?topic=calls-pass-by-reference-c-only)

**Comment by JonasBiener** [comment]
Wird so gemacht, danke für den Hinweis!
Ich hatte nicht auf dem Schirm, dass man die  Referenzierung auch in den Funktionsparametern vornehmen kann.
