### ISSUE TITLE
Offset PWM to have minimum motor speed > 0

### ISSUE THREAD

**Issue by teeheee** [Robotics-Competence-Center-Illertal-e-V/RocciBoard-Library#2]
In der Goldboard Lib war immer ein Offset auf dem Motorspeed wenn er != 0 gesetzt wurde. Dadurch haben die Motoren sich immer gedreht selbst wenn die PWM Werte sehr klein waren.
Bei PWM=10 dreht sich zB nix.

**Comment by JonasBiener** [comment]
Klingt sinnvoll, vor allem um "sinnlosen Motorstrom" zu beheben. Werde ich nach einem Test einfügen.
